### ISSUE TITLE
Change "Venmo Link" to "Venmo" or "Venmo Handle"

### ISSUE THREAD

**Issue by vinnie4k** [cuappdev/resell-react-native#120]
![image](https://github.com/cuappdev/resell-react-native/assets/75594943/b50c91e1-fc59-4901-a18b-73cb28e4434d)

**Comment by Archit404Error** [comment]
+1, especially because I believe if the user enters the @ symbol like @vinnie4k did in the screenshot above, the "pay with venmo" button will not work (since it opens up a URL with the user's Venmo username, which does not contain the @ sign)

So the input box should also probably have an "@" symbol on the left hand side to let the user know they shouldn't enter the symbol manually
